#!/bin/sh
#it just insert a nouse value,
#beacuse the git config --unset value do not delete the section,if the section do not have items.
git config --global diff.nouse 0

diffParameter=$1
#if [ $1 = "-c" ]; then
#diffParameter="--cached"
#else
#diffParameter=""
#fi

oldDiff=`git config --global diff.external`
echo 'oldDiff' $oldDiff

diffDirNum=0
diffDir="/tmp/gitDiff"${diffDirNum}
while [ -d "$diffDir" ] ; do
	diffDirNum=`expr ${diffDirNum} + 1`
	diffDir="/tmp/gitDiff"${diffDirNum}
done
#diffDir=${diffDir}${diffDirNum}
echo 'diffDir :' ${diffDir}

export diffDir
oldDir="old"
newDir="new"
export oldDir
export newDir 
mkdir -p ${diffDir}/$oldDir 
mkdir -p ${diffDir}/$newDir

newDiff='gitMyDiff'

git config --global diff.external /usr/local/bin/$newDiff
echo 'curDiff :'  `git config --global diff.external`
git diff $diffParameter

if [ $oldDiff ]; then
	git config --global diff.external $oldDiff
else
	git config --global --unset diff.external
fi

echo 'curDiff :'  `git config --global diff.external`
meld ${diffDir}/$oldDir ${diffDir}/$newDir

rm $diffDir -rf 
echo 'gitdiff finish'
