#!/bin/sh
#echo $*
oldTargetFile=${diffDir}/${oldDir}/"$1"
mkdir -p `dirname $oldTargetFile`
if [ $2 != '/dev/null' ]; then
    cp "$2" ${diffDir}/${oldDir}/"$1"
fi
tmpDir=`pwd` 
newTargetDir=`dirname ${diffDir}/${newDir}/"${1}"`
mkdir -p $newTargetDir
cd $newTargetDir
if [ ${5:0:4} == '/tmp'  ]; then
    cp "$5" ${diffDir}/${newDir}/"$1"
    echo 'new copy' ${diffDir}/${newDir}/"$1"
elif [ $5 != '/dev/null' ]; then
    ln -s ${tmpDir}/${5}
    echo 'new ln' ${tmpDir}/${5}
fi
cd -
